config/routes.rb
Codealia::Application.routes.draw do

  # scope :blog do
  #   resources :posts do
  #     resources :comments, only: [:create]
  #   end
  # end

  get '/templates/*template_name', to: 'templates#get_template'

  root 'static_pages#index'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/donors', to: 'static_pages#donors', as: 'donors'
  get '/mentors', to: 'static_pages#mentors', as: 'mentors'
  get '/developers', to: 'static_pages#developers', as: 'developers'

  get '/learning/:workshop_id', to: 'learning#show'
  get '/learning/:workshop_id/:part_id', to: 'learning#show'

  get '/legal/terms_and_conditions', to: 'static_pages#terms_and_conditions', as: 'terms_and_conditions'
  get '/html-preview', to: 'static_pages#html_preview', as: 'html_preview'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :post, :body, :name
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments

  validates_presence_of :content, :author, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  # TODO switch to this conditional when the site is
  # translated properly
  # unless Rails.env.test?
  if Rails.env.development?
    def default_url_options(options = {})
      { locale: I18n.locale }
    end
  end

  private

  def set_locale
    # TODO remove the conditional when the site is
    # translated properly
    unless Rails.env.production?
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  layout 'workshops'

  def show
    workshop = params[:workshop_id]
    part = params[:part_id] || 'intro'

    if part == 'intro'
      render "learning/#{workshop}/#{part}", layout: 'two_columns'
    else
      render "learning/#{workshop}/#{part}"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, :except => [ :index, :show] # auth bf all methods except index & show
  # before_action :set_post, only: [:show,  :update, :edit, :destroy] #set post id only for show, edit, update & destroy methods
  before_action :set_post, :except => [:index, :new, :create]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :created_at, :content)
    end

    #Must login to create/edit post
    def authenticate
      #TODO: implement authentication
      authenticate_or_request_with_http_basic do |name, password|
        # name == "admin" && password == "secret"
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'two_columns'

  def index
  end

  def about
    @about = 'About Us'
  end

  def terms_and_conditions
    @title = 'Terms & Conditions'
  end

  def html_preview
    render layout: false
  end

  def instructors
    @title = 'Instructors'
  end

  def developers
    @title = 'Developers'
  end

  def donors
    @title = 'Donors'
  end

  def mentors
    @title = 'Mentors'
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ActionController::Base
  DIRECTORY = 'app/assets/javascripts/templates'

  def get_template
    render file: "#{DIRECTORY}/#{params[:template_name]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end

  def language_switch_link
    locale = (params[:locale] == 'se' ? :en : :se)
    text_for_locale = {
      en: t('layouts.navbar.links.switch_to_EN'),
      se: t('layouts.navbar.links.switch_to_SE'),    }
    raw <<-HTML
      <li>#{link_to(text_for_locale[locale], root_url(locale: locale))}</li>
    HTML
  end

  def workshop_path(workshop, part)
    workshop_id = "workshop-#{workshop}"
    part_id = (part.to_s.match(/\d+/) ? "part-#{part}" : part)
    url_for(action: :show, controller: :learning,
            workshop_id: workshop_id, part_id: part_id)
  end

  def shared_meta_keywords
    'Codealia, Coding for Girls, Women in Technology, Coding for Kids'
  end

  def default_meta_description
    @default_meta_description ||= '' +
    'An Open Source Solution For Technology Education. Codealia seeks to level the playing field by ' +
    'developing a free open-source learning platform with an engaging curriculum targeting young girls. ' +
    'Our interactive program will foster collaboration, teamwork and open communication which will pave ' +
    'the way to future careers in the information technology field.'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/learning_helper.rb
module LearningHelper
  def placeholder_img width, height = nil
    height ||= width
    tag('img', src: "http://placekitten.com/g/#{width}/#{height}")
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/angular-app/passions-editor.html.erb
<div id="passions-editor" style="width: 100%; height: 150px; position: fixed; bottom: 0"></div>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
        <strong>
          Posted <%= time_ago_in_words(comment.created_at) %> ago
        </strong>

        <br/>

      <%= comment.name %>
      <br/>
      <%= comment.body %>

    </p>

<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="list-unstyled">
      <li>Volunteers</li>
      <li><%= link_to 'About Us', about_path %></li>
      <!-- <li>Blog placehoder</li> -->
      <!--<li><a href="#">Contact & support</a></li>-->
    </ul>
  </div>
  <div class="col-md-3">
    <ul class="list-unstyled">
      <li>Organizations</li>
      <li><a href="http://www.agileventures.org">Agile Ventures</a></li>
    </ul>

  </div>

  <div class="col-md-3">
    <ul class="list-unstyled">
      <li>Social Media</li>
      <li><a href="https://www.facebook.com/codealia"><i class="fa fa-facebook fa-custom-social"></i> Facebook</a></li>
      <li><a href="https://twitter.com/codealia"><i class="fa fa-twitter fa-custom-social"></i> Twitter</a></li>
      <li><a href="https://www.pinterest.com/codealia/"><i class="fa fa-pinterest fa-custom-social"></i> Pinterest</a></li>
      <li><a href="https://instagram.com/codealia_learntocode#"><i class="fa fa-instagram fa-custom-social"></i> Instagram</a></li>
    </ul>
  </div>

  <div class="col-md-3">
    <ul class="list-unstyled">
      <li><a href="/legal/terms_and_conditions">Terms of Service</a></li>
      <li><a href="/legal/terms_and_conditions#privacy">Privacy</a></li>
    </ul>
  </div>
</div>

<div class="row">
  The content of this site is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.
</div>

app/views/layouts/_meta_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="<%= "#{shared_meta_keywords}#{ content_for?(:keywords) ? ",#{yield(:keywords)}" : ''}" %>">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta name="author" content="<%= content_for?(:author) ? yield(:author) : 'AgileVentures and Codealia volunteers and contributors' %>">
<% if content_for?(:robots) %>
  <meta name="robots" content="<%= yield(:robots) %>">
<% end %>
<meta name="copyright" content="AgileVentures Nonprofit Ltd.">
<meta name="coverage" content="Worldwide">
<meta name="distribution" content="Global">
<meta name="application-name" content="Codealia Official Website">

<meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'Codealia' %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.original_url %>">
<meta property="og:site_name" content="Codealia">
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta property="og:image" content="<%= image_url 'codealia-logo.png' %>">

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="<%= content_for?(:title) ? yield(:title) : 'Codealia' %>">
<meta name="twitter:url" content="<%= request.original_url %>">
<meta name="twitter:site" content="@Codealia">
<meta name="twitter:image:src" content="<%= image_url 'codealia-logo.png' %>">
<% if content_for?(:twitter_creator) %>
  <meta name="twitter:creator" content="<%= yield(:twitter_creator) %>">
<% end %>
<meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-custom navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">codealia.org</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Workshop 1', workshop_path(1, 'intro') %></li>
      <!-- <li><%= link_to 'Workshop 2', workshop_path(2, 'intro') %></li> -->
    </ul>
    <ul class="nav navbar-nav pull-right">
      <%= language_switch_link unless Rails.env.production? %>
      <li class="active"><a href="#"><%= t('layouts.navbar.links.concept_draft') %></a></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>

app/views/layouts/_shared_head.html.erb
<title><%= content_for?(:title) ? yield(:title) : t('app.title') %></title>
<%= csrf_meta_tags %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="<%= "#{shared_meta_keywords}#{ content_for?(:keywords) ? ",#{yield(:keywords)}" : ''}" %>">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta name="author" content="<%= content_for?(:author) ? yield(:author) : 'AgileVentures and Codealia volunteers and contributors' %>">
<% if content_for?(:robots) %>
  <meta name="robots" content="<%= yield(:robots) %>">
<% end %>
<meta name="copyright" content="AgileVentures Nonprofit Ltd.">
<meta name="coverage" content="Worldwide">
<meta name="distribution" content="Global">
<meta name="application-name" content="Codealia Official Website">

<% social_title = content_for?(:title) ? yield(:title) : 'Codealia' %>
<% social_url = request.original_url %>
<% social_description = content_for?(:description) ? yield(:description) : default_meta_description %>

<meta property="og:title" content="<%= social_title %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= social_url %>">
<meta property="og:site_name" content="Codealia">
<meta property="og:description" content="<%= social_description %>">
<meta property="og:image" content="<%= image_url 'codealia-logo.png' %>">

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="<%= social_title %>">
<meta name="twitter:url" content="<%= social_url %>">
<meta name="twitter:site" content="@Codealia">
<meta name="twitter:image:src" content="<%= image_url 'codealia-logo.png' %>">
<% if content_for?(:twitter_creator) %>
  <meta name="twitter:creator" content="<%= yield(:twitter_creator) %>">
<% end %>
<meta name="twitter:description" content="<%= social_description %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/shared_head' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body ng-app="Codealia">

<div id="wrap">
  <div class="container-fluid" style="min-height: 100%; margin-top: 50px;">
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </div>
  <div id="push"></div>
</div>
<div id="footer">
  <div class="container-fluid">
    <%= render 'layouts/footer' %>
  </div>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-49758753-1', 'codealia.org');
    ga('send', 'pageview');

</script>

</body>
</html>

app/views/layouts/two_columns.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="codealia animated fadeInLeft" style="opacity: 1; z-index: 0;"></div>
  </div>
  <div class="col-sm-8">
    <%= yield %>
  </div>
</div>

<section class="bg-1"></section>

<%= parent_layout 'application' %>

app/views/layouts/workshops.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/shared_head' %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- <link href="/custom.css" rel="stylesheet"> -->
  <%= stylesheet_link_tag "workshop/passion", 'data-turbolink-track' => true %>
  <%= stylesheet_link_tag "codealia-ide", 'data-turbolink-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body ng-app="Codealia">

<div>
  <%= yield %>
  <div cdl-passions-editor></div>
</div>

</body>
</html>

app/views/learning/workshop-1/intro.html.erb
<% title = t('learning.workshop-1.heading.title') %>
<% provide(:title, title) %>

<h2><%= title %></h2>
<div class="well">
  <h3>"Your first site"</h3>
  <p>In the Passion part of the curriculum we focus mainly on
    experiencing the possibilities of web applications and getting
    the kids acquainted with pair programming, presentation skills, etc.</p>

  <p>In WS1 we want... </p>

  <h4>Setup</h4>
  <ul>
    <li>Workshop 1 (90 mins)</li>
    <li>Instructors: 2</li>
    <li>Students: 4 - 10 pairs</li>
  </ul>

  <h4>Instructions:</h4>
  <p>Use the link below to go to the first workshop and see what we can do with a little HTML</p>
  <ul>
    <li><%= link_to 'Workshop 1', workshop_path(1, 1) %></li>
  </ul>
</div>

app/views/learning/workshop-1/part-1.html.erb
<div cdl-preview><%= render 'layouts/ws1_scaffold' %></div>

app/views/learning/workshop-2/intro.html.erb
<% i18n_path = 'learning.workshop-2.intro' %>
<% title = t("learning.workshop-2.heading.title") %>
<% provide(:title, title) %>

<h2><%= title %></h2>
<div class="well">

  <h3>"Hello Social World"</h3>
  <p>In the Passion part of the curriculum we focus mainly on
    experiencing the possibilities of web applications and getting
    the kids acquainted with pair programming, presentation skills, etc.</p>

  <p>In WS2 we want to showcase the concept of software talking to other
    software by making API calls and extracting some content from Instagram. </p>

  <h4>Setup</h4>
  <ul>
    <li>Workshop 2 (90 mins)</li>
    <li>Instructors: 2</li>
    <li>Students: 4 - 10 pairs</li>
  </ul>

  <h4>Resources:</h4>
  <ul>
    <li><%= link_to t("#{i18n_path}.links.part", number: 1), workshop_path(2, 1) %>
      - Instagram API interface to search for user profile and return a instagram userID</li>
    <li><%= link_to t("#{i18n_path}.links.part", number: 2), workshop_path(2, 2) %>
      - The main interface for students to work on. </li>
  </ul>


</div>

app/views/learning/workshop-2/part-1.html.erb
<% provide(:title, 'Instagram UserName to UserID') %>

<div class="container">
    <h1 style="color: white;">Passions - Workshop 2</h1>

    <h4>Let's start with getting a Instagram user ID: </h4>
    <ol>
        <li>Enter your instagram username in the field below to lookup your id.</li>
        <li><strong>Make a note of that number.</strong>
            You are going to need it to master your main assignment for this workshop!</li>
    </ol>
    <!-- Comment or uncomment this section if you want to display a search form-->
    <div class="row form-group searchContainer">
        <div class="col-sm-3">
            <input class="searchBox form-control" placeholder="Search">
        </div>
        <div class="col-sm-2">
            <button class="searchInstagram btn btn-default" rel="user">Search</button>
        </div>
        <div id="searchMessage"></div>
    </div>
    <!-- End search form code -->

    <!-- This is where all the incoming output will be rendered by js -->
    <div id="results" class="row"></div>
    <!-- End of results -->


    <div>
        <hr>
        <footer>
            <small>Codealia.org - Passions Workshop 2 Licenced under the Creative Commons Licence Codealia.org 2014
            </small>
        </footer>
    </div>
</div>
<script src="/workshopOne.js" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#results').workshopOne({call: 'usersearch'}
        );
    });
</script>

app/views/learning/workshop-2/part-2.html.erb
<%= provide(:title, 'Social World') %>

<div class="jumbotron bg-1" cdl-preview>
  <settings data-bg="giftly" data-user="1239267164"></settings>
  <div class="container" style="color: white;">
    <h1>Hello Social World!</h1>

    <h2>Lets show some pictures</h2>
  </div>
</div>
<div class="container">
  <h4>Let's dive into the code - this is your main assignment for today: </h4>
  <ol>
    <li>In the code of the page, please find
      <code>&lt;settings data-bg="skulls"...&gt;</code>
      and change "skulls" to some other background. You can choose any of these backgrounds and you may change
      them as many times as you want:
      <code> photography, skulls, food, lined_paper, giftly</code> or <code>congruent_pentagon</code> - that's a tricky
      one!
      <br/>Play around with those backgrounds until you are satisfied.
    </li>

    <li>Now, within the <code>&lt;settings&gt;</code> tag, there is another data tag with the text <code>data-user="1239267164"</code>
      in it. Change "1239267164" to the number you got on when searching for the user feed you want to display.
    </li>

    <li>Find the <code>&lt;H1&gt;</code> tag on the page. Change the text to how you want to say hello to your
      visitors.
    </li>
    <li>Close to the <code>&lt;H1&gt;</code> tag you'll find a <code>&lt;H2&gt;</code> tag. Make sure that you
      change that text as well. You don't want to keep "Hello Kitty" or do you?.
    </li>
    <li>Finally, find the text you are reading right now and delete it or change it to something you want to say to
      your visitors!
    </li>
  </ol>
  <strong>Don't forget to save your work and always ask your teacher if you feel unsure about what to do!</strong>
  <hr>
  <!-- Comment or uncomment this section if you want to display a search form-->
  <div class="row form-group searchContainer">
    <div class="col-sm-3">
      <input class="searchBox form-control" placeholder="Search">
    </div>
    <div class="col-sm-2">
      <button class="searchInstagram btn btn-default" rel="tag">Search</button>
    </div>
    <div id="searchMessage"></div>
  </div>
  <!-- End search form code -->

  <hr>
  <div id="results" class="row"></div>
  <div>
    <hr>
    <footer>
      <small>Codealia.org - Passions Workshop 2 Licenced under the Creative Commons Licence Codealia.org 2014</small>
    </footer>
  </div>
</div>
<!-- Scripts - needs to be included -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<script src="/workshopOne.js" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function () {
    $('#results').workshopOne({
      //First we get the background keyword and pass that on
      bg: $('settings').data('bg'),
      //If we want to show the feed for a hashtag:
      //hashtag: $('settings').data('hashtag'),
      mode: 'user',
      userID: $('settings').data('user')
      //If we want to show the feed of a specific user:
      //userID : '1239267164' //Codealia
      //userID : '33647687'  //Paris Hilton
    });
  });
</script>

app/views/posts/_post.html.erb
<h2><%= link_to_unless_current post.title, post %></h2>
<%= simple_format post.author %>
Posted <%= time_ago_in_words(post.created_at) %> ago
<%= simple_format post.content %>

app/views/posts/new.html.erb
<p>New post</p>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/static_pages/index.html.erb
<% i18n_path = 'static_pages.index' %>
<header>
  <h2>i am</h2>
  <h1 style="margin-left: -10px !important;">codealia</h1>
</header>

<div class="well">
  <%= t("#{i18n_path}.text.learning_code_html") %>

  <h3>The Problem</h3>

  <p>Women's representation in the computing and information technology workforce has been falling.</p>

  <p>An imbalanced non-inclusive workforce that fails to embrace the talent of women neglects the fact that women have
    surpassed men in Internet usage since the year 2000.</p>

  <blockquote>"We found that very early on computing is claimed as male territory. At each step from early childhood
    through college, computing is both actively claimed as "guy stuff" by boys and men (and parents), and passively
    ceded by girls and women. The claiming is largely the work of a culture and society that links interest and success
    with computers to boys and men."
    <strong><a href="http://tcla.gseis.ucla.edu/divide/politics/margolis.html">Jane Margolis</a></strong></blockquote>

  <p>Lack of diversity impairs an organization's ability to respond to an increasingly varied global user base. This
    negatively impacts relations with the surrounding community and reduces the organization's ability to respond to
    change.</p>

  <p>Users of IT products are just as likely to be women as men. However, most of these products are created with little
    or no input from female developers. We need broader, more inclusive perspectives in order to achieve better
    results.</p>

  <h3>The Solution</h3>

  <p><!-- We are missing out on half of the customer base for our software products which ought to be built by people who understand the end user.  -->Increasing the number of women software engineers expands the creativity and responsiveness of our workforce.</p>

  <p>Codealia will build out a complete offering - a free open-source palette of tools, guides and lesson plans. </p>

  <p>Individuals and organizations can use Codealia's tools to deliver both web-based and live computer science courses
    targeted towards girls in their communities.</p>

  <p>We'll make the course content fun, interactive and engaging for the next generation of coders!</p>

  <blockquote>"I believe all kids should learn to program, for the same reasons we teach them about photosynthesis and
    chemistry. We don’t expect all of them to become scientists, but they should know how the world works. Today
    software is a very real part of our world embedded in our phones and even our cars."
    <strong><a href="http://techfemme.wordpress.com/2010/12/22/sarah-allen/">Sarah Allen</a></strong></blockquote>
  <!-- <blockquote>"Most people don’t realize how fun it is because of the media stereotypes of what programmers do and what programmers are like.  But most of the first programmers were women.  One example is the ENIAC, which was one of the first computers built to support the war effort.  The hardware was built by two men, but it was programmed by women.  Programming was considered a support role at this time, so they weren’t widely recognized until later." <strong><a href="http://techfemme.wordpress.com/2010/12/22/sarah-allen/">Sarah Allen</a></strong></blockquote> -->

  <!-- <p>Providing practical manuals and promotional guides for instructors and organizers.</p> -->

  <h3>Want to see more women in technology?</h3>

  <p><strong>Join Us</strong> &amp; help us in blazing the trail for women in Computer Science!</p>


  <!-- <p>As Software engineers - we are worried that there are way to few female colleagues in our industry
    - and we sincerely believe that it leads to poor quality of the software we produce. </p>

  <p>We want to help to change that and make computer science attractive for young women and help them
    pursue careers within information technology.</p>

  <h3>The Problem</h3>

  <p>Women’s representation in the computing and information technology workforce has been falling. </p>

  <h3>The Solution</h3>

  <p>The goal of the project is to create a palette of tools that individuals and organizations can use to deliver
    courses in their communities. Our goal is to offer a complete solution - we will build and open source
    comprehensive course content, web-based tools for learning, practical information for instructors and organizers
    and marketing materials.</p> -->

</div>
<div class="row">
  <div class="col-md-4">
    <img src="<%= image_path('CTA1.png')%>">
    <h2 class="text-center">Donors</h2>
    <p>Codealia has a strong emphasis on collaboration, co-operation and self-organising teams. With your contributions Codealia will be able to change the world.</p>
  </div>

  <div class="col-md-4">
    <img src="<%= image_path('CTA3.png')%>">
    <h2 class="text-center">Mentors</h2>
    <p>We welcome everyone who wants to get involved in our project.</p>
  </div>

  <div class="col-md-4">
    <img src="<%= image_path('CTA2.png')%>">
    <h2 class="text-center">Developers</h2>
    <p>Help us build out an open source, comprehensive course providing web-based tools for learning and practical information for instructors and organisers.</p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="cta"><%= link_to 'Learn more', donors_path, class: 'btn btn-default' %></div>
  </div>
  <div class="col-md-4">
    <div class="cta"><%= link_to 'Learn more', mentors_path, class: 'btn btn-default' %></div>
  </div>
  <div class="col-md-4">
    <div class="cta"><%= link_to 'Learn more', developers_path, class: 'btn btn-default' %></div>
  </div>
</div>


<!-- End of main content -->